vich_uploader:
    db_driver: orm # or mongodb
    
    mappings:
        car:
            uri_prefix: /uploads/image
            upload_destination: '%kernel.project_dir%/public/uploads/image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer