#index:
#    path: /
#    controller: App\Controller\DefaultController::index
cars:
    path: /cars
    controller: App\Controller\YourController::cars
add_to_order:
    path: /add-to-order/{id}
    controller: App\Controller\ProductController::addToOrder

home:
    path: /home
    controller: App\Controller\HomeController::index
